/* ────────────────────────────────────
   VALORANT AGENT DATA
   ──────────────────────────────────── */

export type ValRole = 'Duelist' | 'Controller' | 'Sentinel' | 'Initiator'

export const VAL_ROLES_DEF = [
  { id: 'All', label: 'All', color: 'text-foreground', bgColor: 'bg-white/10', dotColor: '' },
  {
    id: 'Duelist',
    label: 'Duelist',
    color: 'text-red-400',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    dotColor: 'bg-red-400',
  },
  {
    id: 'Controller',
    label: 'Controller',
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/30',
    dotColor: 'bg-purple-400',
  },
  {
    id: 'Sentinel',
    label: 'Sentinel',
    color: 'text-green-400',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    dotColor: 'bg-green-400',
  },
  {
    id: 'Initiator',
    label: 'Initiator',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    dotColor: 'bg-cyan-400',
  },
]

export const VAL_ROLE_COLORS: Record<
  ValRole,
  { text: string; bg: string; border: string; dot: string }
> = {
  Duelist: {
    text: 'text-red-400',
    bg: 'bg-red-500/10',
    border: 'border-red-500/30',
    dot: 'bg-red-400',
  },
  Controller: {
    text: 'text-purple-400',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/30',
    dot: 'bg-purple-400',
  },
  Sentinel: {
    text: 'text-green-400',
    bg: 'bg-green-500/10',
    border: 'border-green-500/30',
    dot: 'bg-green-400',
  },
  Initiator: {
    text: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    dot: 'bg-cyan-400',
  },
}

export const VALORANT_AGENTS = [
  {
    name: 'Jett',
    role: 'Duelist' as ValRole,
    winrate: 52.4,
    pickrate: 18.2,
    banrate: 3.1,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.8,
    kda: 1.2,
  },
  {
    name: 'Reyna',
    role: 'Duelist' as ValRole,
    winrate: 50.8,
    pickrate: 16.9,
    banrate: 2.5,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.1,
    kda: 1.4,
  },
  {
    name: 'Raze',
    role: 'Duelist' as ValRole,
    winrate: 49.5,
    pickrate: 13.2,
    banrate: 0.8,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.3,
    kda: 1.1,
  },
  {
    name: 'Phoenix',
    role: 'Duelist' as ValRole,
    winrate: 48.2,
    pickrate: 5.9,
    banrate: 0.3,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.5,
    kda: 0.9,
  },
  {
    name: 'Iso',
    role: 'Duelist' as ValRole,
    winrate: 51.1,
    pickrate: 8.4,
    banrate: 1.2,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.6,
    kda: 1.1,
  },
  {
    name: 'Omen',
    role: 'Controller' as ValRole,
    winrate: 51.8,
    pickrate: 15.5,
    banrate: 1.8,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.4,
    kda: 0.8,
  },
  {
    name: 'Brimstone',
    role: 'Controller' as ValRole,
    winrate: 50.5,
    pickrate: 11.3,
    banrate: 0.9,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 0.7,
  },
  {
    name: 'Astra',
    role: 'Controller' as ValRole,
    winrate: 49.2,
    pickrate: 7.8,
    banrate: 0.5,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.4,
    kda: 0.6,
  },
  {
    name: 'Harbor',
    role: 'Controller' as ValRole,
    winrate: 47.9,
    pickrate: 3.4,
    banrate: 0.2,
    tier: 'C' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 0.5,
  },
  {
    name: 'Clove',
    role: 'Controller' as ValRole,
    winrate: 50.9,
    pickrate: 9.1,
    banrate: 1.1,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.7,
    kda: 0.9,
  },
  {
    name: 'Killjoy',
    role: 'Sentinel' as ValRole,
    winrate: 51.5,
    pickrate: 14.1,
    banrate: 2.2,
    tier: 'S' as const,
    trend: 'stable' as const,
    trendChange: 0.2,
    kda: 0.9,
  },
  {
    name: 'Cypher',
    role: 'Sentinel' as ValRole,
    winrate: 50.3,
    pickrate: 9.7,
    banrate: 1.5,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.3,
    kda: 0.8,
  },
  {
    name: 'Chamber',
    role: 'Sentinel' as ValRole,
    winrate: 49.0,
    pickrate: 8.5,
    banrate: 1.0,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.6,
    kda: 1.0,
  },
  {
    name: 'Deadlock',
    role: 'Sentinel' as ValRole,
    winrate: 47.5,
    pickrate: 2.8,
    banrate: 0.1,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.7,
    kda: 0.6,
  },
  {
    name: 'Sova',
    role: 'Initiator' as ValRole,
    winrate: 51.2,
    pickrate: 12.8,
    banrate: 1.6,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.5,
    kda: 0.9,
  },
  {
    name: 'Fade',
    role: 'Initiator' as ValRole,
    winrate: 50.1,
    pickrate: 10.5,
    banrate: 1.3,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.1,
    kda: 0.8,
  },
  {
    name: 'Gekko',
    role: 'Initiator' as ValRole,
    winrate: 48.8,
    pickrate: 6.1,
    banrate: 0.4,
    tier: 'B' as const,
    trend: 'up' as const,
    trendChange: 0.2,
    kda: 0.7,
  },
  {
    name: 'Kayo',
    role: 'Initiator' as ValRole,
    winrate: 47.8,
    pickrate: 5.2,
    banrate: 0.3,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.4,
    kda: 0.6,
  },
  {
    name: 'Skye',
    role: 'Initiator' as ValRole,
    winrate: 50.6,
    pickrate: 7.9,
    banrate: 0.7,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 1.1,
  },
  {
    name: 'Vyse',
    role: 'Sentinel' as ValRole,
    winrate: 51.3,
    pickrate: 11.2,
    banrate: 2.8,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 1.1,
    kda: 0.9,
  },
]
