import type { LoLChampion } from './constants'

/* ────────────────────────────────────
   LOL CHAMPION DATA
   ──────────────────────────────────── */

export const LOL_CHAMPIONS: LoLChampion[] = [
  // Top
  {
    name: 'Aatrox',
    role: 'Top',
    winrate: 51.8,
    pickrate: 14.2,
    banrate: 8.1,
    tier: 'S',
    trend: 'up',
    trendChange: 0.5,
    games: 245000,
  },
  {
    name: 'Garen',
    role: 'Top',
    winrate: 50.5,
    pickrate: 13.1,
    banrate: 1.2,
    tier: 'A',
    trend: 'stable',
    trendChange: 0.1,
    games: 198000,
  },
  {
    name: 'Darius',
    role: 'Top',
    winrate: 49.8,
    pickrate: 11.2,
    banrate: 3.5,
    tier: 'B',
    trend: 'down',
    trendChange: -0.3,
    games: 172000,
  },
  {
    name: "K'Sante",
    role: 'Top',
    winrate: 51.2,
    pickrate: 9.8,
    banrate: 4.2,
    tier: 'A',
    trend: 'up',
    trendChange: 0.7,
    games: 156000,
  },
  {
    name: 'Mordekaiser',
    role: 'Top',
    winrate: 48.5,
    pickrate: 6.4,
    banrate: 2.1,
    tier: 'C',
    trend: 'down',
    trendChange: -0.8,
    games: 98000,
  },
  // Jungle
  {
    name: 'Lee Sin',
    role: 'Jungle',
    winrate: 50.9,
    pickrate: 11.7,
    banrate: 5.5,
    tier: 'S',
    trend: 'stable',
    trendChange: 0.2,
    games: 210000,
  },
  {
    name: 'Viego',
    role: 'Jungle',
    winrate: 50.2,
    pickrate: 9.8,
    banrate: 6.8,
    tier: 'A',
    trend: 'up',
    trendChange: 0.4,
    games: 178000,
  },
  {
    name: 'Graves',
    role: 'Jungle',
    winrate: 49.7,
    pickrate: 7.3,
    banrate: 1.5,
    tier: 'B',
    trend: 'down',
    trendChange: -0.2,
    games: 132000,
  },
  {
    name: 'Jarvan IV',
    role: 'Jungle',
    winrate: 51.1,
    pickrate: 8.9,
    banrate: 3.2,
    tier: 'A',
    trend: 'up',
    trendChange: 0.6,
    games: 165000,
  },
  {
    name: "Rek'Sai",
    role: 'Jungle',
    winrate: 50.5,
    pickrate: 5.4,
    banrate: 0.8,
    tier: 'B',
    trend: 'stable',
    trendChange: 0.0,
    games: 98000,
  },
  // Mid
  {
    name: 'Orianna',
    role: 'Mid',
    winrate: 51.3,
    pickrate: 12.5,
    banrate: 2.3,
    tier: 'S',
    trend: 'up',
    trendChange: 0.3,
    games: 220000,
  },
  {
    name: 'Ahri',
    role: 'Mid',
    winrate: 50.6,
    pickrate: 10.9,
    banrate: 1.8,
    tier: 'A',
    trend: 'stable',
    trendChange: 0.1,
    games: 192000,
  },
  {
    name: 'Zed',
    role: 'Mid',
    winrate: 49.2,
    pickrate: 8.6,
    banrate: 2.5,
    tier: 'B',
    trend: 'down',
    trendChange: -0.5,
    games: 148000,
  },
  {
    name: 'Syndra',
    role: 'Mid',
    winrate: 51.5,
    pickrate: 7.8,
    banrate: 1.2,
    tier: 'A',
    trend: 'up',
    trendChange: 0.8,
    games: 135000,
  },
  {
    name: 'Yasuo',
    role: 'Mid',
    winrate: 47.8,
    pickrate: 12.3,
    banrate: 7.9,
    tier: 'C',
    trend: 'down',
    trendChange: -0.6,
    games: 215000,
  },
  // ADC
  {
    name: 'Jinx',
    role: 'ADC',
    winrate: 52.1,
    pickrate: 16.8,
    banrate: 9.2,
    tier: 'S',
    trend: 'up',
    trendChange: 0.4,
    games: 280000,
  },
  {
    name: "Kai'Sa",
    role: 'ADC',
    winrate: 50.8,
    pickrate: 15.3,
    banrate: 5.1,
    tier: 'A',
    trend: 'stable',
    trendChange: 0.1,
    games: 262000,
  },
  {
    name: 'Draven',
    role: 'ADC',
    winrate: 48.2,
    pickrate: 5.1,
    banrate: 0.9,
    tier: 'C',
    trend: 'down',
    trendChange: -0.4,
    games: 89000,
  },
  {
    name: 'Ezreal',
    role: 'ADC',
    winrate: 49.5,
    pickrate: 14.1,
    banrate: 2.2,
    tier: 'B',
    trend: 'stable',
    trendChange: 0.0,
    games: 245000,
  },
  {
    name: 'Aphelios',
    role: 'ADC',
    winrate: 51.6,
    pickrate: 6.7,
    banrate: 3.1,
    tier: 'A',
    trend: 'up',
    trendChange: 0.9,
    games: 118000,
  },
  // Support
  {
    name: 'Thresh',
    role: 'Support',
    winrate: 50.4,
    pickrate: 15.8,
    banrate: 2.8,
    tier: 'A',
    trend: 'stable',
    trendChange: 0.0,
    games: 275000,
  },
  {
    name: 'Nautilus',
    role: 'Support',
    winrate: 51.0,
    pickrate: 12.2,
    banrate: 3.5,
    tier: 'S',
    trend: 'up',
    trendChange: 0.3,
    games: 210000,
  },
  {
    name: 'Lulu',
    role: 'Support',
    winrate: 50.1,
    pickrate: 9.5,
    banrate: 1.1,
    tier: 'A',
    trend: 'down',
    trendChange: -0.2,
    games: 168000,
  },
  {
    name: 'Janna',
    role: 'Support',
    winrate: 49.8,
    pickrate: 7.2,
    banrate: 0.4,
    tier: 'B',
    trend: 'stable',
    trendChange: 0.1,
    games: 125000,
  },
  {
    name: 'Yuumi',
    role: 'Support',
    winrate: 48.5,
    pickrate: 4.8,
    banrate: 12.1,
    tier: 'C',
    trend: 'down',
    trendChange: -0.7,
    games: 82000,
  },
]

export const LOL_PRO_BUILDS = [
  {
    player: 'Faker',
    team: 'T1',
    champion: 'Orianna',
    role: 'Mid',
    winrate: 58.2,
    games: 45,
    items: [
      'Morellonomicon',
      "Rabadon's Deathcap",
      'Void Staff',
      "Zhonya's Hourglass",
      "Rylai's Crystal Scepter",
      'Ionian Boots',
    ],
  },
  {
    player: 'Ruler',
    team: 'Gen.G',
    champion: 'Jinx',
    role: 'ADC',
    winrate: 56.8,
    games: 42,
    items: [
      'Immortal Shieldbow',
      'Infinity Edge',
      "Lord Dominik's Regards",
      'Phantom Dancer',
      'Bloodthirster',
      "Berserker's Greaves",
    ],
  },
  {
    player: 'Zeus',
    team: 'T1',
    champion: 'Aatrox',
    role: 'Top',
    winrate: 55.1,
    games: 38,
    items: [
      'Sundered Sky',
      'Black Cleaver',
      "Sterak's Gage",
      "Death's Dance",
      'Thornmail',
      'Plated Steelcaps',
    ],
  },
  {
    player: 'Canyon',
    team: 'Gen.G',
    champion: 'Lee Sin',
    role: 'Jungle',
    winrate: 57.3,
    games: 41,
    items: [
      "Prowler's Claw",
      'Black Cleaver',
      "Serylda's Grudge",
      'Edge of Night',
      "Death's Dance",
      "Sorcerer's Shoes",
    ],
  },
  {
    player: 'Keria',
    team: 'T1',
    champion: 'Thresh',
    role: 'Support',
    winrate: 54.9,
    games: 44,
    items: [
      'Locket of the Iron Solari',
      'Redemption',
      "Knight's Vow",
      "Dead Man's Plate",
      'Ardent Censer',
      'Boots of Speed',
    ],
  },
  {
    player: 'Chovy',
    team: 'Gen.G',
    champion: 'Ahri',
    role: 'Mid',
    winrate: 59.1,
    games: 36,
    items: [
      'Lich Bane',
      "Rabadon's Deathcap",
      'Void Staff',
      'Horizon Focus',
      'Cosmic Drive',
      "Sorcerer's Shoes",
    ],
  },
]

export const LOL_ITEMS = [
  { name: 'Sundered Sky', gold: 3100 },
  { name: 'Black Cleaver', gold: 3000 },
  { name: "Sterak's Gage", gold: 3100 },
  { name: "Death's Dance", gold: 3100 },
  { name: 'Thornmail', gold: 2700 },
  { name: 'Plated Steelcaps', gold: 1100 },
]
