/* ────────────────────────────────────
   DOTA 2 HERO DATA
   ──────────────────────────────────── */

export type DotaRole = 'Carry' | 'Mid' | 'Offlane' | 'Support' | 'Pos 5'

export const DOTA_ROLES_DEF = [
  { id: 'All', label: 'All', color: 'text-foreground', bgColor: 'bg-white/10', dotColor: '' },
  {
    id: 'Carry',
    label: 'Carry',
    color: 'text-red-400',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    dotColor: 'bg-red-400',
  },
  {
    id: 'Mid',
    label: 'Mid',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    dotColor: 'bg-cyan-400',
  },
  {
    id: 'Offlane',
    label: 'Offlane',
    color: 'text-orange-400',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    dotColor: 'bg-orange-400',
  },
  {
    id: 'Support',
    label: 'Supp',
    color: 'text-green-400',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    dotColor: 'bg-green-400',
  },
  {
    id: 'Pos 5',
    label: 'Pos 5',
    color: 'text-yellow-400',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/30',
    dotColor: 'bg-yellow-400',
  },
]

export const DOTA_ROLE_COLORS: Record<
  DotaRole,
  { text: string; bg: string; border: string; dot: string }
> = {
  Carry: {
    text: 'text-red-400',
    bg: 'bg-red-500/10',
    border: 'border-red-500/30',
    dot: 'bg-red-400',
  },
  Mid: {
    text: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    dot: 'bg-cyan-400',
  },
  Offlane: {
    text: 'text-orange-400',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    dot: 'bg-orange-400',
  },
  Support: {
    text: 'text-green-400',
    bg: 'bg-green-500/10',
    border: 'border-green-500/30',
    dot: 'bg-green-400',
  },
  'Pos 5': {
    text: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    dot: 'bg-yellow-400',
  },
}

export const DOTA2_HEROES = [
  {
    name: 'Pudge',
    role: 'Offlane' as DotaRole,
    winrate: 53.2,
    pickrate: 25.1,
    banrate: 12.5,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.6,
  },
  {
    name: 'Faceless Void',
    role: 'Carry' as DotaRole,
    winrate: 52.8,
    pickrate: 18.5,
    banrate: 8.2,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.4,
  },
  {
    name: 'Earth Spirit',
    role: 'Offlane' as DotaRole,
    winrate: 52.5,
    pickrate: 14.2,
    banrate: 6.8,
    tier: 'S' as const,
    trend: 'stable' as const,
    trendChange: 0.1,
  },
  {
    name: 'Lion',
    role: 'Support' as DotaRole,
    winrate: 52.1,
    pickrate: 16.8,
    banrate: 4.5,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.3,
  },
  {
    name: 'Anti-Mage',
    role: 'Carry' as DotaRole,
    winrate: 51.5,
    pickrate: 12.3,
    banrate: 5.1,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
  },
  {
    name: 'Tidehunter',
    role: 'Offlane' as DotaRole,
    winrate: 51.2,
    pickrate: 11.8,
    banrate: 3.9,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.2,
  },
  {
    name: 'Ogre Magi',
    role: 'Pos 5' as DotaRole,
    winrate: 50.9,
    pickrate: 10.5,
    banrate: 1.2,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
  },
  {
    name: 'Snapfire',
    role: 'Support' as DotaRole,
    winrate: 50.6,
    pickrate: 9.2,
    banrate: 2.8,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.5,
  },
  {
    name: 'Marci',
    role: 'Support' as DotaRole,
    winrate: 50.8,
    pickrate: 11.5,
    banrate: 3.2,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
  },
  {
    name: 'Hoodwink',
    role: 'Mid' as DotaRole,
    winrate: 51.1,
    pickrate: 8.9,
    banrate: 2.1,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.4,
  },
  {
    name: 'Juggernaut',
    role: 'Carry' as DotaRole,
    winrate: 49.8,
    pickrate: 14.5,
    banrate: 4.3,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.2,
  },
  {
    name: 'Sand King',
    role: 'Offlane' as DotaRole,
    winrate: 49.5,
    pickrate: 8.9,
    banrate: 2.5,
    tier: 'B' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
  },
  {
    name: 'Crystal Maiden',
    role: 'Pos 5' as DotaRole,
    winrate: 49.2,
    pickrate: 9.7,
    banrate: 1.8,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.3,
  },
  {
    name: 'Undying',
    role: 'Offlane' as DotaRole,
    winrate: 49.0,
    pickrate: 7.3,
    banrate: 1.5,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.4,
  },
  {
    name: 'Storm Spirit',
    role: 'Mid' as DotaRole,
    winrate: 49.6,
    pickrate: 10.2,
    banrate: 3.8,
    tier: 'B' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
  },
  {
    name: 'Huskar',
    role: 'Carry' as DotaRole,
    winrate: 48.5,
    pickrate: 6.8,
    banrate: 1.2,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.5,
  },
  {
    name: 'Necrophos',
    role: 'Mid' as DotaRole,
    winrate: 48.2,
    pickrate: 5.4,
    banrate: 0.9,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.6,
  },
  {
    name: 'Spirit Breaker',
    role: 'Pos 5' as DotaRole,
    winrate: 47.9,
    pickrate: 4.1,
    banrate: 0.5,
    tier: 'C' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
  },
  {
    name: 'Arc Warden',
    role: 'Mid' as DotaRole,
    winrate: 47.5,
    pickrate: 2.3,
    banrate: 0.3,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.4,
  },
  {
    name: 'Tinker',
    role: 'Mid' as DotaRole,
    winrate: 50.4,
    pickrate: 7.6,
    banrate: 2.9,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.3,
  },
]
