/* ────────────────────────────────────
   TFT COMP DATA
   ──────────────────────────────────── */

export const TFT_COST_ROLES_DEF = [
  { id: 'All', label: 'All', color: 'text-foreground', bgColor: 'bg-white/10', dotColor: '' },
  {
    id: '1',
    label: '$1 Easy',
    color: 'text-gray-400',
    bgColor: 'bg-gray-500/10',
    borderColor: 'border-gray-500/30',
    dotColor: 'bg-gray-400',
  },
  {
    id: '2',
    label: '$2 Easy',
    color: 'text-green-400',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    dotColor: 'bg-green-400',
  },
  {
    id: '3',
    label: '$3 Medium',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    dotColor: 'bg-cyan-400',
  },
  {
    id: '4',
    label: '$4 Hard',
    color: 'text-violet-400',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    dotColor: 'bg-violet-400',
  },
  {
    id: '5',
    label: '$5 Hard',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    dotColor: 'bg-amber-400',
  },
]

export const TFT_COST_COLORS: Record<
  string,
  { text: string; bg: string; border: string; dot: string }
> = {
  '1': {
    text: 'text-gray-400',
    bg: 'bg-gray-500/10',
    border: 'border-gray-500/30',
    dot: 'bg-gray-400',
  },
  '2': {
    text: 'text-green-400',
    bg: 'bg-green-500/10',
    border: 'border-green-500/30',
    dot: 'bg-green-400',
  },
  '3': {
    text: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    dot: 'bg-cyan-400',
  },
  '4': {
    text: 'text-violet-400',
    bg: 'bg-violet-500/10',
    border: 'border-violet-500/30',
    dot: 'bg-violet-400',
  },
  '5': {
    text: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/30',
    dot: 'bg-amber-400',
  },
}

export const TFT_COMPS = [
  {
    name: 'Cybernetic Bash',
    role: '4' as const,
    winrate: 24.5,
    pickrate: 8.4,
    placementRate: 31.2,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 1.2,
    difficulty: 'Easy',
    carryUnits: ['Vi', 'Ezreal', 'Fiora'],
  },
  {
    name: 'KDA Reset',
    role: '5' as const,
    winrate: 23.1,
    pickrate: 7.1,
    placementRate: 28.9,
    tier: 'S' as const,
    trend: 'stable' as const,
    trendChange: 0.2,
    difficulty: 'Hard',
    carryUnits: ['Ahri', 'Ekko', 'Sett'],
  },
  {
    name: 'Pentakill',
    role: '4' as const,
    winrate: 22.8,
    pickrate: 9.2,
    placementRate: 29.5,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.5,
    difficulty: 'Medium',
    carryUnits: ['Karthus', 'Yasuo', 'Kayle'],
  },
  {
    name: 'Edgelord',
    role: '3' as const,
    winrate: 21.5,
    pickrate: 6.8,
    placementRate: 27.8,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.8,
    difficulty: 'Medium',
    carryUnits: ['Zed', 'Nocturne', 'Katarina'],
  },
  {
    name: 'Bruiser',
    role: '2' as const,
    winrate: 20.2,
    pickrate: 10.3,
    placementRate: 25.1,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    difficulty: 'Easy',
    carryUnits: ['Darius', 'Garen', 'Warwick'],
  },
  {
    name: 'Syndicate',
    role: '3' as const,
    winrate: 19.8,
    pickrate: 8.7,
    placementRate: 24.8,
    tier: 'A' as const,
    trend: 'down' as const,
    trendChange: -0.3,
    difficulty: 'Medium',
    carryUnits: ['Twisted Fate', 'Viego', 'Akali'],
  },
  {
    name: 'Academy',
    role: '3' as const,
    winrate: 20.5,
    pickrate: 7.5,
    placementRate: 25.5,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.4,
    difficulty: 'Medium',
    carryUnits: ['Taliyah', 'Nomsy', 'Leona'],
  },
  {
    name: 'Innovator',
    role: '2' as const,
    winrate: 18.9,
    pickrate: 5.9,
    placementRate: 23.9,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.6,
    difficulty: 'Easy',
    carryUnits: ['Ziggs', 'Heimerdinger', 'Lulu'],
  },
  {
    name: 'Mutant',
    role: '1' as const,
    winrate: 17.2,
    pickrate: 6.2,
    placementRate: 22.1,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.5,
    difficulty: 'Easy',
    carryUnits: ['Twitch', 'KogMaw', 'ChoGath'],
  },
  {
    name: 'Socialite',
    role: '2' as const,
    winrate: 16.8,
    pickrate: 5.4,
    placementRate: 21.8,
    tier: 'B' as const,
    trend: 'stable' as const,
    trendChange: 0.1,
    difficulty: 'Easy',
    carryUnits: ['Senna', 'Neeko', 'Nami'],
  },
  {
    name: 'Twinshot',
    role: '1' as const,
    winrate: 17.5,
    pickrate: 7.8,
    placementRate: 22.5,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.2,
    difficulty: 'Easy',
    carryUnits: ['Varus', 'Vayne', 'Cassiopeia'],
  },
  {
    name: 'Sniper',
    role: '3' as const,
    winrate: 16.5,
    pickrate: 4.3,
    placementRate: 21.2,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.4,
    difficulty: 'Hard',
    carryUnits: ['Jinx', 'Ashe', 'Aphelios'],
  },
  {
    name: 'Renegade',
    role: '2' as const,
    winrate: 15.2,
    pickrate: 3.8,
    placementRate: 19.5,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.6,
    difficulty: 'Medium',
    carryUnits: ['Samira', 'Pyke', 'Gangplank'],
  },
  {
    name: 'Scrap',
    role: '1' as const,
    winrate: 14.5,
    pickrate: 3.1,
    placementRate: 18.9,
    tier: 'C' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    difficulty: 'Easy',
    carryUnits: ['Rumble', 'Tristana', 'Fizz'],
  },
  {
    name: 'Arcanist',
    role: '4' as const,
    winrate: 15.0,
    pickrate: 4.5,
    placementRate: 19.2,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.3,
    difficulty: 'Hard',
    carryUnits: ['Syndra', 'Veigar', 'Ryze'],
  },
  {
    name: 'Chem-Baron',
    role: '3' as const,
    winrate: 14.2,
    pickrate: 2.7,
    placementRate: 18.5,
    tier: 'C' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    difficulty: 'Medium',
    carryUnits: ['Singed', 'Twitch', 'Zac'],
  },
]
