export type LoLRole = 'Top' | 'Jungle' | 'Mid' | 'ADC' | 'Support'

const TAG_TO_ROLE: Record<string, LoLRole> = {
  Fighter: 'Top',
  Mage: 'Mid',
  Assassin: 'Mid',
  Marksman: 'ADC',
  Support: 'Support',
  Tank: 'Top',
}

const PRIMARY_ROLES: Record<string, LoLRole> = {
  Aatrox: 'Top',
  Akali: 'Mid',
  Akshan: 'ADC',
  Alistar: 'Support',
  Amumu: 'Jungle',
  Anivia: 'Mid',
  Annie: 'Mid',
  Ashe: 'ADC',
  AurelionSol: 'Mid',
  Azir: 'Mid',
  Bard: 'Support',
  Blitzcrank: 'Support',
  Brand: 'Support',
  Braum: 'Support',
  Caitlyn: 'ADC',
  Camille: 'Top',
  Cassiopeia: 'Mid',
  ChoGath: 'Top',
  Corki: 'Mid',
  Darius: 'Top',
  Diana: 'Jungle',
  Draven: 'ADC',
  DrMundo: 'Top',
  Ekko: 'Jungle',
  Elise: 'Jungle',
  Ezreal: 'ADC',
  Fiddlesticks: 'Jungle',
  Fiora: 'Top',
  Fizz: 'Mid',
  Galio: 'Mid',
  Gangplank: 'Top',
  Garen: 'Top',
  Gnar: 'Top',
  Gragas: 'Jungle',
  Graves: 'Jungle',
  Gwen: 'Top',
  Hecarim: 'Jungle',
  Heimerdinger: 'Mid',
  Illaoi: 'Top',
  Irelia: 'Top',
  Ivern: 'Jungle',
  Janna: 'Support',
  JarvanIV: 'Jungle',
  Jax: 'Top',
  Jayce: 'Top',
  Jhin: 'ADC',
  Jinx: 'ADC',
  Kaisa: 'ADC',
  Kalista: 'ADC',
  Karma: 'Support',
  Karthus: 'Jungle',
  Katarina: 'Mid',
  Kayle: 'Top',
  Kayn: 'Jungle',
  Kennen: 'Top',
  Khazix: 'Jungle',
  Kindred: 'Jungle',
  Kled: 'Top',
  KogMaw: 'ADC',
  LeBlanc: 'Mid',
  LeeSin: 'Jungle',
  Leona: 'Support',
  Lissandra: 'Mid',
  Lucian: 'ADC',
  Lulu: 'Support',
  Lux: 'Mid',
  Malphite: 'Top',
  Malzahar: 'Mid',
  Maokai: 'Top',
  MasterYi: 'Jungle',
  MissFortune: 'ADC',
  Mordekaiser: 'Top',
  Morgana: 'Support',
  Nami: 'Support',
  Nasus: 'Top',
  Nautilus: 'Support',
  Neeko: 'Support',
  Nidalee: 'Jungle',
  Nocturne: 'Jungle',
  Nunu: 'Jungle',
  Olaf: 'Top',
  Orianna: 'Mid',
  Ornn: 'Top',
  Pantheon: 'Top',
  Poppy: 'Jungle',
  Pyke: 'Support',
  Quinn: 'Top',
  Rakan: 'Support',
  Rammus: 'Jungle',
  RekSai: 'Jungle',
  Renekton: 'Top',
  Rengar: 'Jungle',
  Riven: 'Top',
  Rumble: 'Top',
  Ryze: 'Mid',
  Sejuani: 'Jungle',
  Senna: 'Support',
  Sett: 'Top',
  Shaco: 'Jungle',
  Shen: 'Top',
  Shyvana: 'Jungle',
  Singed: 'Top',
  Sion: 'Top',
  Sivir: 'ADC',
  Skarner: 'Jungle',
  Sona: 'Support',
  Soraka: 'Support',
  Swain: 'Top',
  Sylas: 'Mid',
  Syndra: 'Mid',
  TahmKench: 'Support',
  Taliyah: 'Mid',
  Talon: 'Mid',
  Taric: 'Support',
  Teemo: 'Top',
  Thresh: 'Support',
  Tristana: 'ADC',
  Trundle: 'Top',
  Tryndamere: 'Top',
  TwistedFate: 'Mid',
  Twitch: 'ADC',
  Udyr: 'Jungle',
  Urgot: 'Top',
  Varus: 'ADC',
  Vayne: 'ADC',
  Veigar: 'Mid',
  VelKoz: 'Mid',
  Vi: 'Jungle',
  Viego: 'Jungle',
  Viktor: 'Mid',
  Vladimir: 'Top',
  Volibear: 'Top',
  Warwick: 'Jungle',
  Xerath: 'Mid',
  XinZhao: 'Jungle',
  Yasuo: 'Mid',
  Yone: 'Mid',
  Yorick: 'Top',
  Yuumi: 'Support',
  Zac: 'Jungle',
  Zed: 'Mid',
  Zeri: 'ADC',
  Ziggs: 'Mid',
  Zilean: 'Support',
  Zyra: 'Support',
}

export function getLoLRole(championId: string, tags: string[]): LoLRole {
  const primary = PRIMARY_ROLES[championId]
  if (primary) return primary
  for (const tag of tags) {
    const mapped = TAG_TO_ROLE[tag]
    if (mapped) return mapped
  }
  return 'Mid'
}

export function patchLabelFromVersion(version: string): string {
  return version.split('.').slice(0, 2).join('.')
}
