import {
  Crosshair,
  Crown,
  Eye,
  LayoutDashboard,
  Rocket,
  RotateCcw,
  Shield,
  Sparkles,
  Star,
  Swords,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Wrench,
  Zap,
} from 'lucide-react'
import type { Game, GameId, NavGameItem, SidebarSection } from './types'

export const NAV_GAMES: NavGameItem[] = [
  {
    id: 'lol',
    name: 'League of Legends',
    shortName: 'LoL',
    icon: Swords,
    dotColor: 'bg-emerald-400',
    badge: { text: 'HOT', color: 'text-white', bgColor: 'bg-red-500' },
  },
  { id: 'valorant', name: 'Valorant', shortName: 'VAL', icon: Crosshair, dotColor: 'bg-red-400' },
  { id: 'rematch', name: 'Rematch', shortName: 'RM', icon: RotateCcw, dotColor: 'bg-green-400' },
  { id: 'tft', name: 'Teamfight Tactics', shortName: 'TFT', icon: Crown, dotColor: 'bg-amber-400' },
  {
    id: 'deadlock',
    name: 'Deadlock',
    shortName: 'DL',
    icon: Zap,
    dotColor: 'bg-violet-400',
    badge: { text: 'NEW', color: 'text-white', bgColor: 'bg-violet-500' },
  },
  {
    id: 'wow',
    name: 'World of Warcraft',
    shortName: 'WoW',
    icon: Shield,
    dotColor: 'bg-purple-400',
  },
  {
    id: 'helldivers2',
    name: 'Helldivers 2',
    shortName: 'HD2',
    icon: Rocket,
    dotColor: 'bg-orange-400',
  },
  {
    id: '2xko',
    name: '2XKO',
    shortName: '2XKO',
    icon: Swords,
    dotColor: 'bg-rose-400',
    badge: { text: 'SOON™', color: 'text-white', bgColor: 'bg-rose-500' },
  },
]

export const SIDEBAR_SECTIONS: Record<GameId, SidebarSection[]> = {
  lol: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'champions', label: 'Champions', icon: Swords },
    { id: 'builds', label: 'Builds', icon: Wrench },
    { id: 'runes', label: 'Runes', icon: Sparkles },
    { id: 'counters', label: 'Counters', icon: Target },
    { id: 'pro-builds', label: 'Pro Builds', icon: Star },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Game', icon: Eye },
  ],
  valorant: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'agents', label: 'Agents', icon: Users },
    { id: 'builds', label: 'Builds', icon: Wrench },
    { id: 'abilities', label: 'Abilities', icon: Sparkles },
    { id: 'counters', label: 'Counters', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Game', icon: Eye },
  ],
  rematch: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'champions', label: 'Fighters', icon: Swords },
    { id: 'builds', label: 'Builds', icon: Wrench },
    { id: 'runes', label: 'Perks', icon: Sparkles },
    { id: 'counters', label: 'Counters', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Match', icon: Eye },
  ],
  tft: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'champions', label: 'Champions', icon: Swords },
    { id: 'comps', label: 'Comps', icon: Wrench },
    { id: 'augments', label: 'Augments', icon: Sparkles },
    { id: 'traits', label: 'Traits', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Game', icon: Eye },
  ],
  deadlock: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'heroes', label: 'Heroes', icon: Swords },
    { id: 'builds', label: 'Builds', icon: Wrench },
    { id: 'abilities', label: 'Abilities', icon: Sparkles },
    { id: 'counters', label: 'Counters', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Game', icon: Eye },
  ],
  wow: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'classes', label: 'Classes', icon: Swords },
    { id: 'builds', label: 'Builds', icon: Wrench },
    { id: 'talents', label: 'Talents', icon: Sparkles },
    { id: 'encounters', label: 'Encounters', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Game', icon: Eye },
  ],
  helldivers2: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'weapons', label: 'Weapons', icon: Swords },
    { id: 'stratagems', label: 'Stratagems', icon: Wrench },
    { id: 'perks', label: 'Perks', icon: Sparkles },
    { id: 'enemies', label: 'Enemies', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Game', icon: Eye },
  ],
  '2xko': [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'fighters', label: 'Fighters', icon: Swords },
    { id: 'combos', label: 'Combos', icon: Wrench },
    { id: 'moves', label: 'Moves', icon: Sparkles },
    { id: 'counters', label: 'Counters', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Match', icon: Eye },
  ],
  dota2: [
    { id: 'home', label: 'Home', icon: LayoutDashboard },
    { id: 'heroes', label: 'Heroes', icon: Swords },
    { id: 'builds', label: 'Builds', icon: Wrench },
    { id: 'abilities', label: 'Abilities', icon: Sparkles },
    { id: 'counters', label: 'Counters', icon: Target },
    { id: 'tier-list', label: 'Tier List', icon: TrendingUp },
    { id: 'leaderboards', label: 'Leaderboards', icon: Trophy },
    { id: 'live-game', label: 'Live Game', icon: Eye },
  ],
}

export const GAMES: Game[] = [
  {
    id: 'lol',
    name: 'League of Legends',
    shortName: 'LoL',
    tagline: 'Builds, counters, runes y más',
    badge: { text: 'HOT', color: 'bg-red-500 text-white' },
    image: '/games/lol.png',
    gradientBg: 'from-emerald-900/40 to-emerald-600/20',
    accentColor: 'emerald',
    accentHover: 'hover:border-emerald-500/60',
    icon: Swords,
    iconColor: 'text-emerald-400',
    features: [
      { title: 'Campeones rastreados', stat: '167+', sub: 'con datos activos' },
      { title: 'Tier List actualizada', stat: '24h', sub: 'última actualización' },
      { title: 'Win Rate promedio', stat: '50.3%', sub: 'todas las rangos' },
      { title: 'Partidas analizadas', stat: '2.5M+', sub: 'este parche' },
    ],
    tierList: [
      {
        tier: 'S',
        color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
        champions: [
          { name: 'Aatrox', winrate: '51.8%', pick: '14.2%', role: 'Top' },
          { name: 'Jinx', winrate: '52.1%', pick: '16.8%', role: 'ADC' },
          { name: 'Orianna', winrate: '51.3%', pick: '12.5%', role: 'Mid' },
          { name: 'Lee Sin', winrate: '50.9%', pick: '11.7%', role: 'Jungle' },
        ],
      },
      {
        tier: 'A',
        color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
        champions: [
          { name: 'Garen', winrate: '50.5%', pick: '13.1%', role: 'Top' },
          { name: "Kai'Sa", winrate: '50.8%', pick: '15.3%', role: 'ADC' },
          { name: 'Ahri', winrate: '50.6%', pick: '10.9%', role: 'Mid' },
          { name: 'Viego', winrate: '50.2%', pick: '9.8%', role: 'Jungle' },
        ],
      },
      {
        tier: 'B',
        color: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
        champions: [
          { name: 'Darius', winrate: '49.8%', pick: '11.2%', role: 'Top' },
          { name: 'Ezreal', winrate: '49.5%', pick: '14.1%', role: 'ADC' },
          { name: 'Zed', winrate: '49.2%', pick: '8.6%', role: 'Mid' },
          { name: 'Graves', winrate: '49.7%', pick: '7.3%', role: 'Jungle' },
        ],
      },
      {
        tier: 'C',
        color: 'bg-violet-500/20 text-violet-400 border-violet-500/30',
        champions: [
          { name: 'Mordekaiser', winrate: '48.5%', pick: '6.4%', role: 'Top' },
          { name: 'Draven', winrate: '48.2%', pick: '5.1%', role: 'ADC' },
          { name: 'Yasuo', winrate: '47.8%', pick: '12.3%', role: 'Mid' },
          { name: 'Ivern', winrate: '48.0%', pick: '1.9%', role: 'Jungle' },
        ],
      },
    ],
  },
  {
    id: 'tft',
    name: 'Teamfight Tactics',
    shortName: 'TFT',
    tagline: 'Comps, augments y posicionamiento',
    image: '/games/tft.png',
    gradientBg: 'from-amber-900/40 to-amber-600/20',
    accentColor: 'amber',
    accentHover: 'hover:border-amber-500/60',
    icon: Crown,
    iconColor: 'text-amber-400',
    features: [
      { title: 'Comps disponibles', stat: '200+', sub: 'meta y off-meta' },
      { title: 'Augments rastreados', stat: '150+', sub: 'por set actual' },
      { title: 'Top 4 Rate promedio', stat: '+12%', sub: 'usando comps óptimas' },
      { title: 'Partidas analizadas', stat: '800K+', sub: 'este set' },
    ],
    tierList: [
      {
        tier: 'S',
        color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
        champions: [
          { name: 'Cybernetic Bash', winrate: '31.2%', pick: '8.4%', role: 'Comp' },
          { name: 'KDA Reset', winrate: '28.9%', pick: '7.1%', role: 'Comp' },
          { name: 'Pentakill', winrate: '29.5%', pick: '9.2%', role: 'Comp' },
          { name: 'Edgelord', winrate: '27.8%', pick: '6.8%', role: 'Comp' },
        ],
      },
      {
        tier: 'A',
        color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
        champions: [
          { name: 'Bruiser', winrate: '25.1%', pick: '10.3%', role: 'Comp' },
          { name: 'Syndicate', winrate: '24.8%', pick: '8.7%', role: 'Comp' },
          { name: 'Academy', winrate: '25.5%', pick: '7.5%', role: 'Comp' },
          { name: 'Innovator', winrate: '23.9%', pick: '5.9%', role: 'Comp' },
        ],
      },
      {
        tier: 'B',
        color: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
        champions: [
          { name: 'Mutant', winrate: '22.1%', pick: '6.2%', role: 'Comp' },
          { name: 'Socialite', winrate: '21.8%', pick: '5.4%', role: 'Comp' },
          { name: 'Twinshot', winrate: '22.5%', pick: '7.8%', role: 'Comp' },
          { name: 'Sniper', winrate: '21.2%', pick: '4.3%', role: 'Comp' },
        ],
      },
      {
        tier: 'C',
        color: 'bg-violet-500/20 text-violet-400 border-violet-500/30',
        champions: [
          { name: 'Renegade', winrate: '19.5%', pick: '3.8%', role: 'Comp' },
          { name: 'Scrap', winrate: '18.9%', pick: '3.1%', role: 'Comp' },
          { name: 'Arcanist', winrate: '19.2%', pick: '4.5%', role: 'Comp' },
          { name: 'Chem-Baron', winrate: '18.5%', pick: '2.7%', role: 'Comp' },
        ],
      },
    ],
  },
  {
    id: 'valorant',
    name: 'Valorant',
    shortName: 'VAL',
    tagline: 'Agentes, mapas y estrategias',
    image: '/games/valorant.png',
    gradientBg: 'from-red-900/40 to-red-600/20',
    accentColor: 'red',
    accentHover: 'hover:border-red-500/60',
    icon: Crosshair,
    iconColor: 'text-red-400',
    features: [
      { title: 'Agentes rastreados', stat: '25+', sub: 'con guías activas' },
      { title: 'Mapas activos', stat: '14', sub: 'pool competitivo' },
      { title: 'Win Rate promedio', stat: '51.1%', sub: 'rango Diamond+' },
      { title: 'Partidas analizadas', stat: '1.2M+', sub: 'esta temporada' },
    ],
    tierList: [
      {
        tier: 'S',
        color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
        champions: [
          { name: 'Jett', winrate: '52.4%', pick: '18.2%', role: 'Duelist' },
          { name: 'Omen', winrate: '51.8%', pick: '15.5%', role: 'Controller' },
          { name: 'Killjoy', winrate: '51.5%', pick: '14.1%', role: 'Sentinel' },
          { name: 'Sova', winrate: '51.2%', pick: '12.8%', role: 'Initiator' },
        ],
      },
      {
        tier: 'A',
        color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
        champions: [
          { name: 'Reyna', winrate: '50.8%', pick: '16.9%', role: 'Duelist' },
          { name: 'Brimstone', winrate: '50.5%', pick: '11.3%', role: 'Controller' },
          { name: 'Cypher', winrate: '50.3%', pick: '9.7%', role: 'Sentinel' },
          { name: 'Fade', winrate: '50.1%', pick: '10.5%', role: 'Initiator' },
        ],
      },
      {
        tier: 'B',
        color: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
        champions: [
          { name: 'Raze', winrate: '49.5%', pick: '13.2%', role: 'Duelist' },
          { name: 'Astra', winrate: '49.2%', pick: '7.8%', role: 'Controller' },
          { name: 'Chamber', winrate: '49.0%', pick: '8.5%', role: 'Sentinel' },
          { name: 'Gekko', winrate: '48.8%', pick: '6.1%', role: 'Initiator' },
        ],
      },
      {
        tier: 'C',
        color: 'bg-violet-500/20 text-violet-400 border-violet-500/30',
        champions: [
          { name: 'Phoenix', winrate: '48.2%', pick: '5.9%', role: 'Duelist' },
          { name: 'Harbor', winrate: '47.9%', pick: '3.4%', role: 'Controller' },
          { name: 'Deadlock', winrate: '47.5%', pick: '2.8%', role: 'Sentinel' },
          { name: 'Kayo', winrate: '47.8%', pick: '5.2%', role: 'Initiator' },
        ],
      },
    ],
  },
  {
    id: 'deadlock',
    name: 'Deadlock',
    shortName: 'DL',
    tagline: 'Héroes, items y metajuego',
    badge: { text: 'NEW', color: 'bg-blue-500 text-white' },
    image: '/games/deadlock.png',
    gradientBg: 'from-violet-900/40 to-violet-600/20',
    accentColor: 'violet',
    accentHover: 'hover:border-violet-500/60',
    icon: Zap,
    iconColor: 'text-violet-400',
    features: [
      { title: 'Héroes disponibles', stat: '30+', sub: 'con builds activas' },
      { title: 'Guías de heroes', stat: '500+', sub: 'creadas por la comunidad' },
      { title: 'Win Rate promedio', stat: '50.8%', sub: 'rango Ascendant+' },
      { title: 'Partidas analizadas', stat: '300K+', sub: 'datos creciendo' },
    ],
    tierList: [
      {
        tier: 'S',
        color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
        champions: [
          { name: 'Seven', winrate: '53.1%', pick: '22.5%', role: 'Carry' },
          { name: 'Abrams', winrate: '52.8%', pick: '18.1%', role: 'Tank' },
          { name: 'Viscous', winrate: '52.2%', pick: '15.3%', role: 'Support' },
          { name: 'Dynamo', winrate: '51.9%', pick: '12.7%', role: 'Initiator' },
        ],
      },
      {
        tier: 'A',
        color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
        champions: [
          { name: 'Grey Talon', winrate: '51.2%', pick: '14.8%', role: 'Carry' },
          { name: 'Ksenia', winrate: '50.9%', pick: '11.2%', role: 'Flex' },
          { name: 'Mo & Krill', winrate: '50.6%', pick: '9.8%', role: 'Support' },
          { name: 'Wraith', winrate: '50.3%', pick: '10.5%', role: 'Assassin' },
        ],
      },
      {
        tier: 'B',
        color: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
        champions: [
          { name: 'Lash', winrate: '49.8%', pick: '13.5%', role: 'Fighter' },
          { name: 'Bebop', winrate: '49.5%', pick: '11.9%', role: 'Support' },
          { name: 'Mirage', winrate: '49.2%', pick: '8.4%', role: 'Flex' },
          { name: 'McGinnis', winrate: '49.0%', pick: '7.6%', role: 'Tank' },
        ],
      },
      {
        tier: 'C',
        color: 'bg-violet-500/20 text-violet-400 border-violet-500/30',
        champions: [
          { name: 'Haze', winrate: '48.2%', pick: '6.1%', role: 'Assassin' },
          { name: 'Ivy', winrate: '47.9%', pick: '5.5%', role: 'Support' },
          { name: 'Pocket', winrate: '47.5%', pick: '4.2%', role: 'Support' },
          { name: 'Shiv', winrate: '47.8%', pick: '5.8%', role: 'Carry' },
        ],
      },
    ],
  },
  {
    id: 'dota2',
    name: 'Dota 2',
    shortName: 'DOTA',
    tagline: 'Héroes, drafts y estrategias',
    image: '/games/dota2.png',
    gradientBg: 'from-rose-900/40 to-rose-600/20',
    accentColor: 'rose',
    accentHover: 'hover:border-rose-500/60',
    icon: Shield,
    iconColor: 'text-rose-400',
    features: [
      { title: 'Héroes disponibles', stat: '124+', sub: 'todos con datos' },
      { title: 'Drafts analizados', stat: '10K+', sub: 'partidas pro' },
      { title: 'Win Rate promedio', stat: '50.5%', sub: 'rango Divine+' },
      { title: 'Partidas analizadas', stat: '1.8M+', sub: 'este parche' },
    ],
    tierList: [
      {
        tier: 'S',
        color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
        champions: [
          { name: 'Pudge', winrate: '53.2%', pick: '25.1%', role: 'Offlane' },
          { name: 'Faceless Void', winrate: '52.8%', pick: '18.5%', role: 'Carry' },
          { name: 'Earth Spirit', winrate: '52.5%', pick: '14.2%', role: 'Offlane' },
          { name: 'Lion', winrate: '52.1%', pick: '16.8%', role: 'Support' },
        ],
      },
      {
        tier: 'A',
        color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
        champions: [
          { name: 'Anti-Mage', winrate: '51.5%', pick: '12.3%', role: 'Carry' },
          { name: 'Tidehunter', winrate: '51.2%', pick: '11.8%', role: 'Offlane' },
          { name: 'Ogre Magi', winrate: '50.9%', pick: '10.5%', role: 'Support' },
          { name: 'Snapfire', winrate: '50.6%', pick: '9.2%', role: 'Support' },
        ],
      },
      {
        tier: 'B',
        color: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
        champions: [
          { name: 'Juggernaut', winrate: '49.8%', pick: '14.5%', role: 'Carry' },
          { name: 'Sand King', winrate: '49.5%', pick: '8.9%', role: 'Offlane' },
          { name: 'Crystal Maiden', winrate: '49.2%', pick: '9.7%', role: 'Support' },
          { name: 'Undying', winrate: '49.0%', pick: '7.3%', role: 'Offlane' },
        ],
      },
      {
        tier: 'C',
        color: 'bg-violet-500/20 text-violet-400 border-violet-500/30',
        champions: [
          { name: 'Huskar', winrate: '48.5%', pick: '6.8%', role: 'Carry' },
          { name: 'Necrophos', winrate: '48.2%', pick: '5.4%', role: 'Mid' },
          { name: 'Spirit Breaker', winrate: '47.9%', pick: '4.1%', role: 'Support' },
          { name: 'Arc Warden', winrate: '47.5%', pick: '2.3%', role: 'Mid' },
        ],
      },
    ],
  },
  {
    id: 'rematch',
    name: 'Rematch',
    shortName: 'RM',
    tagline: 'Revive el clásico RPG competitivo',
    image: undefined,
    gradientBg: 'from-green-900/40 to-green-600/20',
    accentColor: 'green',
    accentHover: 'hover:border-green-500/60',
    icon: RotateCcw,
    iconColor: 'text-green-400',
    isComingSoon: true,
    features: [
      { title: 'Clases disponibles', stat: '12+', sub: 'datos iniciales' },
      { title: 'Builds comunitarios', stat: '50+', sub: 'en desarrollo' },
      { title: 'Habilidades rastreadas', stat: '200+', sub: 'por clase' },
      { title: 'Matchups analizados', stat: 'Pronto', sub: 'pvp data' },
    ],
  },
  {
    id: 'wow',
    name: 'World of Warcraft',
    shortName: 'WoW',
    tagline: 'Raids, Mythic+ y PvP analytics',
    image: undefined,
    gradientBg: 'from-purple-900/40 to-purple-600/20',
    accentColor: 'purple',
    accentHover: 'hover:border-purple-500/60',
    icon: Shield,
    iconColor: 'text-purple-400',
    isComingSoon: true,
    features: [
      { title: 'Clases rastreadas', stat: '13', sub: 'todas las especializaciones' },
      { title: 'Dungeons Mythic+', stat: '12', sub: 'mapeo completo' },
      { title: 'Raids activos', stat: '8', sub: 'The War Within' },
      { title: 'Talent builds', stat: '60+', sub: 'por especialización' },
    ],
  },
  {
    id: 'helldivers2',
    name: 'Helldivers 2',
    shortName: 'HD2',
    tagline: 'Armas, stratagems y misiones',
    image: undefined,
    gradientBg: 'from-orange-900/40 to-orange-600/20',
    accentColor: 'orange',
    accentHover: 'hover:border-orange-500/60',
    icon: Rocket,
    iconColor: 'text-orange-400',
    isComingSoon: true,
    features: [
      { title: 'Armas catalogadas', stat: '80+', sub: 'con estadísticas' },
      { title: 'Stratagems', stat: '40+', sub: 'tier list y loadouts' },
      { title: 'Enemigos analizados', stat: '35+', sub: 'debilidades y stats' },
      { title: 'Misiones', stat: '12', sub: 'operaciones activas' },
    ],
  },
  {
    id: '2xko',
    name: '2XKO',
    shortName: '2XKO',
    tagline: 'Combos, tiers y matchup data',
    image: undefined,
    gradientBg: 'from-rose-900/40 to-rose-600/20',
    accentColor: 'rose',
    accentHover: 'hover:border-rose-500/60',
    icon: Swords,
    iconColor: 'text-rose-400',
    isComingSoon: true,
    features: [
      { title: 'Fighters disponibles', stat: '20+', sub: 'datos iniciales' },
      { title: 'Frame data', stat: 'En desarrollo', sub: 'próximamente' },
      { title: 'Combos documentados', stat: '100+', sub: 'por luchador' },
      { title: 'Matchup charts', stat: 'Pronto', sub: 'pvp analysis' },
    ],
  },
]
