/* ────────────────────────────────────
   DEADLOCK HERO DATA
   ──────────────────────────────────── */

export type DlRole = 'Carry' | 'Tank' | 'Support' | 'Flex' | 'Initiator' | 'Assassin'

export const DL_ROLES_DEF = [
  { id: 'All', label: 'All', color: 'text-foreground', bgColor: 'bg-white/10', dotColor: '' },
  {
    id: 'Carry',
    label: 'Carry',
    color: 'text-red-400',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    dotColor: 'bg-red-400',
  },
  {
    id: 'Tank',
    label: 'Tank',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    dotColor: 'bg-amber-400',
  },
  {
    id: 'Support',
    label: 'Support',
    color: 'text-green-400',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/30',
    dotColor: 'bg-green-400',
  },
  {
    id: 'Flex',
    label: 'Flex',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    dotColor: 'bg-cyan-400',
  },
  {
    id: 'Initiator',
    label: 'Initiator',
    color: 'text-violet-400',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    dotColor: 'bg-violet-400',
  },
  {
    id: 'Assassin',
    label: 'Assassin',
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/10',
    borderColor: 'border-rose-500/30',
    dotColor: 'bg-rose-400',
  },
]

export const DL_ROLE_COLORS: Record<
  DlRole,
  { text: string; bg: string; border: string; dot: string }
> = {
  Carry: {
    text: 'text-red-400',
    bg: 'bg-red-500/10',
    border: 'border-red-500/30',
    dot: 'bg-red-400',
  },
  Tank: {
    text: 'text-amber-400',
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/30',
    dot: 'bg-amber-400',
  },
  Support: {
    text: 'text-green-400',
    bg: 'bg-green-500/10',
    border: 'border-green-500/30',
    dot: 'bg-green-400',
  },
  Flex: {
    text: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/30',
    dot: 'bg-cyan-400',
  },
  Initiator: {
    text: 'text-violet-400',
    bg: 'bg-violet-500/10',
    border: 'border-violet-500/30',
    dot: 'bg-violet-400',
  },
  Assassin: {
    text: 'text-rose-400',
    bg: 'bg-rose-500/10',
    border: 'border-rose-500/30',
    dot: 'bg-rose-400',
  },
}

export const DEADLOCK_HEROES = [
  {
    name: 'Seven',
    role: 'Carry' as DlRole,
    winrate: 53.1,
    pickrate: 22.5,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.9,
    kda: 3.2,
  },
  {
    name: 'Abrams',
    role: 'Tank' as DlRole,
    winrate: 52.8,
    pickrate: 18.1,
    tier: 'S' as const,
    trend: 'stable' as const,
    trendChange: 0.1,
    kda: 4.5,
  },
  {
    name: 'Viscous',
    role: 'Support' as DlRole,
    winrate: 52.2,
    pickrate: 15.3,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.5,
    kda: 5.1,
  },
  {
    name: 'Dynamo',
    role: 'Initiator' as DlRole,
    winrate: 51.9,
    pickrate: 12.7,
    tier: 'S' as const,
    trend: 'up' as const,
    trendChange: 0.4,
    kda: 3.8,
  },
  {
    name: 'Grey Talon',
    role: 'Carry' as DlRole,
    winrate: 51.2,
    pickrate: 14.8,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 2.9,
  },
  {
    name: 'Ksenia',
    role: 'Flex' as DlRole,
    winrate: 50.9,
    pickrate: 11.2,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.3,
    kda: 3.5,
  },
  {
    name: 'Mo & Krill',
    role: 'Support' as DlRole,
    winrate: 50.6,
    pickrate: 9.8,
    tier: 'A' as const,
    trend: 'down' as const,
    trendChange: -0.2,
    kda: 4.8,
  },
  {
    name: 'Wraith',
    role: 'Assassin' as DlRole,
    winrate: 50.3,
    pickrate: 10.5,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 2.5,
  },
  {
    name: 'Mirage',
    role: 'Flex' as DlRole,
    winrate: 50.1,
    pickrate: 8.4,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.6,
    kda: 3.1,
  },
  {
    name: 'Yamato',
    role: 'Carry' as DlRole,
    winrate: 50.8,
    pickrate: 13.1,
    tier: 'A' as const,
    trend: 'stable' as const,
    trendChange: 0.1,
    kda: 2.8,
  },
  {
    name: 'Lash',
    role: 'Flex' as DlRole,
    winrate: 49.8,
    pickrate: 13.5,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.3,
    kda: 2.6,
  },
  {
    name: 'Bebop',
    role: 'Support' as DlRole,
    winrate: 49.5,
    pickrate: 11.9,
    tier: 'B' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 4.2,
  },
  {
    name: 'McGinnis',
    role: 'Tank' as DlRole,
    winrate: 49.0,
    pickrate: 7.6,
    tier: 'B' as const,
    trend: 'down' as const,
    trendChange: -0.4,
    kda: 4.0,
  },
  {
    name: 'Shiv',
    role: 'Carry' as DlRole,
    winrate: 47.8,
    pickrate: 5.8,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.6,
    kda: 2.2,
  },
  {
    name: 'Haze',
    role: 'Assassin' as DlRole,
    winrate: 48.2,
    pickrate: 6.1,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.5,
    kda: 2.1,
  },
  {
    name: 'Ivy',
    role: 'Support' as DlRole,
    winrate: 47.9,
    pickrate: 5.5,
    tier: 'C' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 4.5,
  },
  {
    name: 'Pocket',
    role: 'Support' as DlRole,
    winrate: 47.5,
    pickrate: 4.2,
    tier: 'C' as const,
    trend: 'down' as const,
    trendChange: -0.3,
    kda: 5.0,
  },
  {
    name: 'Vindicta',
    role: 'Assassin' as DlRole,
    winrate: 50.5,
    pickrate: 7.3,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.7,
    kda: 2.8,
  },
  {
    name: 'Holliday',
    role: 'Carry' as DlRole,
    winrate: 49.2,
    pickrate: 9.6,
    tier: 'B' as const,
    trend: 'stable' as const,
    trendChange: 0.0,
    kda: 3.0,
  },
  {
    name: 'Patron',
    role: 'Tank' as DlRole,
    winrate: 51.5,
    pickrate: 10.2,
    tier: 'A' as const,
    trend: 'up' as const,
    trendChange: 0.5,
    kda: 4.3,
  },
]
